name: "AppImage"

on:
  workflow_call:
    inputs:
      build-id:
        description: 'Identifier for workflows and caching'
        type: string
        required: true
      cpm-cache-version:
        description: "CPM Cache Version"
        type: string
        required: true
      devel:
        description: 'Development mode (disables update checker)'
        type: string
        required: true
      force_pgo:
        description: 'Force PGO builds'
        type: string
        required: true

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}
  BUILD_ID: ${{ inputs.build-id }}

jobs:
  set-matrix:
    name: "Generate AppImage Matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
      compiler: ${{ steps.set.outputs.compiler }}
    steps:
      - id: set
        run: |
          BASE='[{"runs-on": "ubuntu-latest", "target": "amd64"},{"runs-on": "ubuntu-latest", "target": "steamdeck"}'
          ARM=',{"runs-on": "ubuntu-24.04-arm", "target": "aarch64"}'

          if [ "${{ env.DISABLE_ARM }}" != true ]; then
            BASE="${BASE}${ARM}"
          fi

          EXTRA=',{"runs-on": "ubuntu-latest", "target": "legacy"},{"runs-on": "ubuntu-latest", "target": "rog-ally"}'

          if [ "${{ inputs.devel }}" != "true" ]; then
            MATRIX="${BASE}${EXTRA}]"
          else
            MATRIX="${BASE}]"
          fi

          echo $MATRIX
          echo "matrix=${MATRIX}" >> $GITHUB_OUTPUT

          PGO='{"compiler": "clang", "compiler-opt": "-pgo"}'
          CLANG='{"compiler": "clang"}'
          GCC='{"compiler": "gcc"}'

          if [ "${{ inputs.devel }}" != "true" ] || [ "${{ inputs.force_pgo }}" = "true" ]; then
            COMPILER="[${GCC},${PGO}]"
          else
            COMPILER="[${GCC}]"
          fi

          echo $COMPILER
          echo "compiler=${COMPILER}" >> $GITHUB_OUTPUT

  linux:
    name: "AppImage ${{ matrix.os.target }} ${{ matrix.compiler.compiler }}${{ matrix.compiler.compiler-opt }}"
    needs: [set-matrix]
    runs-on: ${{ matrix.os.runs-on }}
    container:
      image: ghcr.io/pkgforge-dev/archlinux:latest
      options: --privileged --device /dev/fuse

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
        compiler: ${{ fromJson(needs.set-matrix.outputs.compiler) }}

    env:
      TARGET: "${{ matrix.os.target }}"
      COMPILER: "${{ matrix.compiler.compiler }}"
      PGO_TARGET: "${{ matrix.compiler.compiler-opt }}"
      FULL_TARGET: ${{ matrix.os.target }}-${{ matrix.compiler.compiler }}${{ matrix.compiler.compiler-opt }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          key: ${{ runner.os }}-${{ env.FULL_TARGET }}
          version: ${{ inputs.cpm-cache-version }}

      - name: Install dependencies
        run: ./.ci/linux/deps.sh
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Configure
        run:  .ci/common/configure.sh -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Build
        run: cmake --build build

      - name: Package
        run: ./.ci/linux/package.sh
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: linux-${{ env.FULL_TARGET }}
          path: ./artifacts/*.AppImage*
