name: "Linux"

on:
  workflow_call:
    inputs:
      build-id:
        description: "build id"
        type: string
        required: true
      cpm-cache-version:
        description: "CPM cache version (e.g. v7)"
        type: string
        required: true
      devel:
        description: 'development build'
        type: string
        required: true
      force_pgo:
        description: 'test PGO builds'
        type: string
        required: true
      matrix:
        description: 'matrix platform'
        type: string
        required: true

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}
  BUILD_ID: ${{ inputs.build-id }}

jobs:
  linux:
    name: "${{ matrix.compiler.pretty-name }} ${{ matrix.compiler.arch }} ${{ matrix.compiler.program }} ${{ matrix.compiler.target }}"
    runs-on: ${{ matrix.compiler.runs-on }}
    container:
      image: ${{ matrix.compiler.container }}
      options: --privileged --device /dev/fuse
    strategy:
      fail-fast: false
      matrix:
        compiler: ${{ fromJson(inputs.matrix) }}

    env:
      TARGET: "${{ matrix.compiler.arch }}"
      COMPILER: "${{ matrix.compiler.program }}"
      PGO_TARGET: "${{ matrix.compiler.target }}"
      FULL_ARCH: ${{ matrix.compiler.arch }}-${{ matrix.compiler.program }}-${{ matrix.compiler.target }}
      ID: "${{ matrix.compiler.id }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Install dependencies
        run: |
          chmod a+x ./.ci/linux/deps.sh
          ./.ci/linux/deps.sh
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          key: ${{ runner.os }}-${{ matrix.compiler.arch }}-${{ matrix.compiler.program }}
          version: ${{ inputs.cpm-cache-version }}

      - name: Configure
        if: ${{ matrix.compiler.system == 'linux' }}
        run:  .ci/common/configure.sh -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Configure Room
        if: ${{ matrix.compiler.system == 'room' }}
        run:  cmake -S . -B build -G Ninja -DYUZU_STATIC_ROOM=ON -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Build
        if: ${{ matrix.compiler.system == 'linux' || matrix.compiler.system == 'room' }}
        run: cmake --build build

      - name: Package Room
        if: ${{ matrix.compiler.system == 'room' }}
        run: |
          src=build/bin/eden-room
          dst=artifacts/"eden-room-${{ matrix.compiler.arch }}-unknown-linux-musl"

          mkdir -p artifacts
          mv "$src" "$dst"
          strip "$dst"

      - name: Package
        if: ${{ matrix.compiler.system == 'linux' }}
        run: ./.ci/linux/package.sh
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Upload artifacts
        if: ${{ matrix.compiler.system == 'linux' }}
        uses: actions/upload-artifact@v6.0.0
        with:
          name: linux-${{ matrix.compiler.arch }}-${{ matrix.compiler.program }}-${{ matrix.compiler.target }}
          path: ./*.AppImage*

      - name: Build
        if: ${{ startsWith(matrix.compiler.system, 'debian') || startsWith(matrix.compiler.system, 'ubuntu') }}
        shell: bash
        run: |
          chmod a+x ./.ci/deb/makedeb.sh
          ./.ci/deb/makedeb.sh
        env:
          ARCH: ${{ matrix.compiler.arch }}
          DEB_NAME: ${{ matrix.compiler.pretty-name }}

      - name: Upload artifacts
        if: ${{ startsWith(matrix.compiler.system, 'debian') || startsWith(matrix.compiler.system, 'ubuntu') }}
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{ matrix.compiler.system }}-${{ matrix.compiler.arch }}
          path: ./*.deb

      - name: Upload artifacts
        if: ${{ matrix.compiler.system == 'room' }}
        uses: actions/upload-artifact@v6.0.0
        with:
          name: room-${{ matrix.arch }}
          path: artifacts/*
