name: "Linux"

on:
  workflow_call:
    inputs:
      build-id:
        description: 'Identifier for workflows and caching'
        type: string
        required: true
      cpm-cache-version:
        description: 'CPM Cache Version'
        type: string
        required: true
      devel:
        description: 'Development mode (disables update checker)'
        type: string
        required: true
      force_pgo:
        description: 'Force PGO builds'
        type: string
        required: true
      matrix:
        description: 'Generated Matrix to each platform'
        type: string
        required: true

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}
  BUILD_ID: ${{ inputs.build-id }}

jobs:
  linux:
    name: "${{ matrix.compiler.system-pretty }} (${{ matrix.compiler.package-target }})"
    runs-on: "${{ matrix.compiler.runs-on }}"
    container:
      image: "${{ matrix.compiler.container }}"
      options: --privileged --device /dev/fuse -v "${{ github.workspace }}":"${{ github.workspace }}"
    strategy:
      fail-fast: false
      matrix:
        compiler: ${{ fromJson(inputs.matrix) }}

    env:
      TARGET: "${{ matrix.compiler.target }}"
      COMPILER: "${{ matrix.compiler.compiler }}"
      COMPILER_OPT: "${{ matrix.compiler.compiler-opt }}"
      PACKAGE_TARGET: "${{ matrix.compiler.package-target }}"
      SYSTEM_PRETTY: "${{ matrix.compiler.system-pretty }}"
      GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Install dependencies
        if: ${{ matrix.compiler.id == 'linux' }}
        run: ./.ci/linux/deps.sh

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          key: ${{ matrix.compiler.system }}-${{ matrix.compiler.package-target }}
          version: ${{ inputs.cpm-cache-version }}

      - name: Configure
        if: ${{ matrix.compiler.id == 'linux' }}
        run:  .ci/common/configure.sh -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Build
        if: ${{ matrix.compiler.id == 'linux' }}
        run: cmake --build build

      - name: Package
        if: ${{ matrix.compiler.id == 'linux' }}
        run: ./.ci/linux/package.sh

      - name: Build
        if: ${{ matrix.compiler.id == 'debian' }}
        run: ./.ci/debian/makedeb.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{ matrix.compiler.system }}-${{ matrix.compiler.package-target }}
          path: ./artifacts/*
